% Auto-generated by cameraCalibrator app on 05-Jun-2019
%-------------------------------------------------------


% Define images to process
imageFileNames = {'C:\Users\Franek\Documents\MATLAB\1.png',...
    'C:\Users\Franek\Documents\MATLAB\2.png',...
    'C:\Users\Franek\Documents\MATLAB\3.png',...
    'C:\Users\Franek\Documents\MATLAB\4.png',...
    'C:\Users\Franek\Documents\MATLAB\5.png',...
    'C:\Users\Franek\Documents\MATLAB\6.png',...
    'C:\Users\Franek\Documents\MATLAB\7.png',...
    'C:\Users\Franek\Documents\MATLAB\8.png',...
    'C:\Users\Franek\Documents\MATLAB\9.png',...
    'C:\Users\Franek\Documents\MATLAB\10.png',...
    };
% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Read the first image to obtain image size
originalImage = imread(imageFileNames{1});
[mrows, ncols, ~] = size(originalImage);

% Generate world coordinates of the corners of the squares
squareSize = 28;  % in units of 'millimeters'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% View reprojection errors
h1=figure; showReprojectionErrors(cameraParams);

% Visualize pattern locations
h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, cameraParams);

% For example, you can use the calibration data to remove effects of lens distortion.
undistortedImage = undistortImage(originalImage, cameraParams);

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('MeasuringPlanarObjectsExample')
% showdemo('StructureFromMotionExample')
